// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8mT2nprDXuxWY601lgLykmXTuRwZvI1c',
    appId: '1:663224385952:web:478d5c4eaa7876e80de4c5',
    messagingSenderId: '663224385952',
    projectId: 'tasky-4eaa0',
    authDomain: 'tasky-4eaa0.firebaseapp.com',
    storageBucket: 'tasky-4eaa0.firebasestorage.app',
    measurementId: 'G-CGCB22PDR7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTpPF9QDm8mRBxaOg9bMVOPsbEycE0qRQ',
    appId: '1:663224385952:android:702902a79aa461570de4c5',
    messagingSenderId: '663224385952',
    projectId: 'tasky-4eaa0',
    storageBucket: 'tasky-4eaa0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdw6eGbHpcq5ecIeTooWIj1ScAP-tjx98',
    appId: '1:663224385952:ios:fef4f576135623e80de4c5',
    messagingSenderId: '663224385952',
    projectId: 'tasky-4eaa0',
    storageBucket: 'tasky-4eaa0.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );
}
